# Replace with your Databricks details
host = "dbc-4126b4fb-8f6e.cloud.databricks.com"
token = "dapi4bd4d8d83f62bb1b5ecde80eda867029"
http_path = "/sql/1.0/warehouses/a05e70836ba1cc0f"


# Add Gemini API key
gemini_api_key = "AIzaSyDep9dONub590y_XKXar5AGdxU_66hQrzA"

duckdb_path = "data/mydb.duckdb"



