OPENAI_API_KEY = "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"

GEMINI_API_KEY = "AIzaSyDep9dONub590y_XKXar5AGdxU_66hQrzA"


